//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using static Курсовая.Controllers.ДокладчикиController;

    public partial class Докладчики
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Докладчики()
        {
            this.Паспорт = "7312000000";
            this.Учебное_заведение = "УлГПУ";
            this.Курс = 2;
            this.Научный_руководитель = "Озерова Д. К.";
            this.Доклады = new HashSet<Доклады>();
        }

        [Required(ErrorMessage = "Пожалуйста, введите ID докладчика")]
        [UniqueIdDokl(ErrorMessage ="Докладчик с таким ID уже существует")]
        [DisplayName(displayName:"ID докладчика")]
        public int ID_докладчика { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите серию и номер паспорта")]
        [RegularExpression(@"^(\d{10})$", ErrorMessage = "Неправильный формат серии и номера паспорта ")]
        public string Паспорт { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите дату рождения")]
        [DataType(DataType.Date)]
        [DisplayName(displayName: "Дата рождения")]
        public System.DateTime Дата_рождения { get; set; }

        [DisplayName(displayName: "Учебное заведение")]
        public string Учебное_заведение { get; set; }
        public Nullable<int> Курс { get; set; }

        [DisplayName(displayName: "Научный руководитель")]
        public string Научный_руководитель { get; set; }
    
        public virtual Участники Участники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Доклады> Доклады { get; set; }
    }
}
