//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Зона
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Зона()
        {
            this.Название = "Киноконцертный зал \"Тарелка";
            this.Предназначение = "Проведение торждественной части";
            this.Технический_специалист = "Лёвин А. В.";
            this.Техника = "Микрофон, проектор, колонки";
            this.Обслуживающий_персонал = new HashSet<Обслуживающий_персонал>();
        }


        [DisplayName(displayName: "ID зоны")]
        public int ID_зоны { get; set; }
        public string Название { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите предназначение")]
        public string Предназначение { get; set; }

        [DisplayName(displayName: "Технический специалист")]
        public string Технический_специалист { get; set; }
        public string Техника { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите ID места нахождения")]
        [DisplayName(displayName: "ID места нахождения")]
        public int ID_места_нахождения { get; set; }
    
        public virtual Место_проведения Место_проведения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Обслуживающий_персонал> Обслуживающий_персонал { get; set; }
    }
}
