//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Конференция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Конференция()
        {
            this.Название_конференции = "Краеведческая конференция \"Наш край родной\"";
            this.Основная_тема = "История родного края";
            this.Организация = "Ульяновский государственный технический университет";
            this.Город = "Ульяновск";
            this.Аудитория = "14";
            this.Рабочий_язык_конференции = "Русский";
            this.Ссылка_на_сайт = "www.konf.ru";
            this.Место_проведения = new HashSet<Место_проведения>();
            this.Сборник = new HashSet<Сборник>();
            this.Спонсоры = new HashSet<Спонсоры>();
            this.Участники = new HashSet<Участники>();
        }


        [Required(ErrorMessage = "Пожалуйста, введите ID конференции")]
        [DisplayName(displayName: "ID конференции")]
        public int ID_конференции { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите название конференции")]
        [DisplayName(displayName: "Название конференции")]
        public string Название_конференции { get; set; }

        [DisplayName(displayName: "Основная тема")]
        public string Основная_тема { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите начало даты проведения")]
        [DisplayName(displayName: "Дата проведения (Начало)")]
        [DataType(DataType.Date)]
        public System.DateTime Дата_проведения_Начало { get; set; }

        [DisplayName(displayName: "Дата проведения (Конец)")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Дата_проведения_Конец { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите организацию")]
        public string Организация { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите город")]
        public string Город { get; set; }
        public string Аудитория { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите рабочий язык конференции")]
        [DisplayName(displayName: "Рабочий язык конференции")]
        public string Рабочий_язык_конференции { get; set; }

        [DisplayName(displayName: "Ссылка на сайт")]
        public string Ссылка_на_сайт { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Место_проведения> Место_проведения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сборник> Сборник { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Спонсоры> Спонсоры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Участники> Участники { get; set; }
    }
}
