//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using static Курсовая.Controllers.Обслуживающий_персоналController;

    public partial class Обслуживающий_персонал
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Обслуживающий_персонал()
        {
            this.Обязанности = "Рассадка гостей";
            this.Стоимость_услуг = 200m;
        }

        [UniqueIdPers(ErrorMessage ="Персонал с таким ID уже существует")]
        [DisplayName(displayName: "ID сотрудника")]
        public int ID_сотрудника { get; set; }

        [Required(ErrorMessage = "Пожалуйста, выберете ответственную зону")]
        [DisplayName(displayName: "Ответственная зона")]
        public int Ответственная_зона { get; set; }

        [Required(ErrorMessage = "Пожалуйста, перечислите обязанности")]
        public string Обязанности { get; set; }

        [DisplayName(displayName: "Стоимость услуг")]
        public Nullable<decimal> Стоимость_услуг { get; set; }
    
        public virtual Зона Зона { get; set; }
        public virtual Участники Участники { get; set; }
    }
}
