//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using static Курсовая.Controllers.ОрганизаторыController;

    public partial class Организаторы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Организаторы()
        {
            this.Должность = "Доцент";
            this.Обязанность = "Рассылка приглашений";
            this.Комиссия = "Программная";
        }
    
        [UniqueIdOrg(ErrorMessage ="Организатор с таким ID уже существует")]
        [DisplayName(displayName: "ID организатора")]
        public int ID_организатора { get; set; }
        public string Должность { get; set; }

        [Required(ErrorMessage = "Пожалуйста, перечислите обязанности")]
        public string Обязанность { get; set; }

        [Required(ErrorMessage = "Пожалуйста, выберете комиссию")]
        public string Комиссия { get; set; }
    
        public virtual Участники Участники { get; set; }
    }
}
