//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using static Курсовая.Controllers.СборникController;

    public partial class Сборник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сборник()
        {
            this.Название_сборника = "Наш родной край";
            this.Издательский_центр = "ООО \"Лань\"";
            this.РИНЦ = true;
            this.Стоимость = 500m;
            this.Количество_страниц = 30;
            this.Электронный_или_печатный_вариант = "Печатный";
            this.Рассылка_докладчикам = true;
        }

        [Required(ErrorMessage = "Пожалуйста, введите ID сборника")]
        [DisplayName(displayName: "ID сборника")]
        public int ID_сборник { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите ID конференции")]
        [DisplayName(displayName: "ID конференции")]
        [UniqueIdKonf(ErrorMessage = "Данная конференция уже имеет сборник")]
        public int ID_конференции { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите название сборника")]
        [DisplayName(displayName: "Название сборника")]
        public string Название_сборника { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите издательский центр")]
        [DisplayName(displayName: "Издательский центр")]
        public string Издательский_центр { get; set; }
        public bool РИНЦ { get; set; }
        public Nullable<decimal> Стоимость { get; set; }

        [DisplayName(displayName: "Количество страниц")]
        public Nullable<int> Количество_страниц { get; set; }

        [Required(ErrorMessage = "Пожалуйста, выберете вариант")]
        [DisplayName(displayName: "Электронный/печатный вариант")]
        public string Электронный_или_печатный_вариант { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите дату выпуска")]
        [DisplayName(displayName: "Дата выпуска")]
        [DataType(DataType.Date)]
        public System.DateTime Дата_выпуска { get; set; }

        [DisplayName(displayName: "Рассылка докладчикам")]
        public bool Рассылка_докладчикам { get; set; }
    
        public virtual Конференция Конференция { get; set; }
    }


}
