//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Участники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Участники()
        {
            this.Фамилия = "Иванов";
            this.Имя = "Иван";
            this.Отчество = "Иванович";
            this.Телефон = "8929777777";
            this.Почта = "ivanov@yandex.ru";
        }

        [Required(ErrorMessage = "Пожалуйста, введите ID участника")]
        [DisplayName(displayName: "ID участника")]
        public int ID_участника { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите ID конференции")]
        [DisplayName(displayName: "ID конференции")]
        public int ID_конференции { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите фамилию")]
        public string Фамилия { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите имя")]
        public string Имя { get; set; }
        public string Отчество { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите номер телефона")]
        [RegularExpression(@"^(\d{11})$", ErrorMessage = "Неправильный формат номера телефона")]
        public string Телефон { get; set; }
        public string Почта { get; set; }
    
        public virtual Докладчики Докладчики { get; set; }
        public virtual Конференция Конференция { get; set; }
        public virtual Обслуживающий_персонал Обслуживающий_персонал { get; set; }
        public virtual Организаторы Организаторы { get; set; }
    }
}
